

#ifndef RB_UI_BASEWINDOW_H
#define RB_UI_BASEWINDOW_H
//qt库
#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPlainTextEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTableView>
#include <QtWidgets/QVBoxLayout>
#include <QtWidgets/QFileDialog>
#include <QtWidgets/QWidget>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QProgressBar>
#include <QPainter>
#include <QTextDocument>
#include <QtCore/QJsonDocument>
#include <QDateTime>
#include <QDialog>
#include <QDir>
#include <QMessageBox>
#include <QProcess>
#include <QTimer>
#include <QThread>
#include <QImage>
#include <QPixmap>
#include <QMutex>
#include "QDebug"
#include "qdebug.h"
#include <QFuture>
#include "QtWebKit/QtWebKit"
//#include <QtConcurrent>
#include <iostream>
#include <ros/node_handle.h>
#include <QGraphicsItem>
#include <QMetaType>

#include "ros/package.h"

using namespace std;

#define  BTN_W 200
#define  BTN_H 50
#define  COMBOX_W 200
#define  COMBOX_H 50
#define  LABLE_STATUS_W 50
#define  LABLE_STATUS_H 50

class gobang_widget:public QWidget{

};

class UiWidget: public QMainWindow {
public:
    UiWidget(ros::NodeHandle* node, QWidget* parent = Q_NULLPTR);
    ~UiWidget();

public:
    //UI流程
    void initQtVal();
    void initUi(QMainWindow *MainWindow);
    void retranslateUi(QMainWindow *MainWindow);

public:
    //ros节点
    ros::NodeHandle* Node;
    //全局变量
    QString tab_qss;
    QString groupBox_qss;
    QString photoPath;
    QString logPath;
public:

    QWidget *centralWidget;
    QHBoxLayout *horizontalLayout_4;
    QVBoxLayout *vLayout_main;
    QHBoxLayout *hLayout_main_11;
    QLabel *label_main_logo;
    QLabel *label_main_title;
    QHBoxLayout *hLayout_main_12;
    QTabWidget *tabWidget;
    QWidget *tab_main;
    QVBoxLayout *verticalLayout_2;
    QVBoxLayout *vLayout_tabmain_1;
    QHBoxLayout *hLayout_tabmain_11;
    QGroupBox *gBox_tabmain_status;
    QHBoxLayout *horizontalLayout_2;
    QGridLayout *gLayout_tabmain_status;
    QLabel *label_tabmain_rbconn;
    QLabel *label_tabmain_rbIsWell;
    QLabel *label_tabmain_rbEnable;
    QLabel *label_tabmain_forceSensor;
    QLabel *label_tabmain_d435iConn;
    QLabel *label_tabmain_hscloudcollection;
    QLabel *label_tabmain_versionBridge;
    QLabel *label_tabmain_gripperbridge;
    QLabel *label_tabmain_fsmBridge;
    QLabel *label_tabmain_shakehandJudge;
    QLabel *label_tabmain_dmBridge;
    QLabel *label_tabmain_plannerBridge;
    QLabel *label_tabmain_motionBridge;
    QLabel *label_tabmain_forcebridge;
    QLabel *label_tabmain_perceptionBridge;
    QLabel *label_tabmain_quickchange;
    QLabel *label_tabmain_pickPlaceBridge;
    QLabel *label_tabmain_asbridge;
    QHBoxLayout *hLayout_tabmain_31;
    QGroupBox *gBox_tabmain_func;
    QHBoxLayout *horizontalLayout_7;
    QPushButton *btn_tabmain_devConn;
    QPushButton *btn_tabmain_start;
    QPushButton *btn_tabmain_sysStop;
    QPushButton *btn_tabmain_sysReset;
    QWidget *tab_fsm;
    QHBoxLayout *horizontalLayout_5;
    QHBoxLayout *hLayout_tab_fsm_1;
    QVBoxLayout *vLayout_tab_fsm_11;
    QTabWidget *tab_tab_fsm;
    QWidget *tab_tab_fsm_people;
    QHBoxLayout *horizontalLayout_16;
    QPlainTextEdit *plainTextEdit_tab_fsm_voiceText;
    QWidget *tab_tab_fsm_yolo6d;
    QHBoxLayout *horizontalLayout_23;
    QLabel *label_tab_fsm_yolo6dImg;
    QVBoxLayout *vLayout_tab_fsm_12;
    QGroupBox *gBox_tab_fsm_status;
    QHBoxLayout *horizontalLayout_22;
    QGridLayout *gLayout_tab_fsm_status;
    QLabel *label_tab_fsm_fivefinger;
    QLabel *label_tab_fsm_exit;
    QLabel *label_tab_fsm_err;
    QLabel *label_tab_fsm_switchgripper;
    QLabel *label_tab_fsm_init;
    QLabel *label_tab_fsm_twofinger;
    QLabel *label_tab_fsm_fourfinger;
    QLabel *label_tab_fsm_nopower;
    QLabel *label_tab_fsm_shakehand;
    QLabel *label_tab_fsm_polish;
    QLabel *label_tab_fsm_grab;
    QLabel *label_tab_fsm_twofingerGrab;
    QTabWidget *tabWidget_tabfsm;
    QWidget *tab_mannalControl;
    QHBoxLayout *horizontalLayout_9;
    QGroupBox *gBox_tab_fsm_operate;
    QVBoxLayout *verticalLayout_11;
    QHBoxLayout *hLayout_tab_fsm_121;
    QPushButton *btn_tab_fsm_run;
    QPushButton *btn_tab_fsm_exit;
    QPushButton *btn_tab_fsm_reset;
    QPushButton *btn_tab_fsm_quickstop;
    QWidget *tab_voiceControl;
    QHBoxLayout *horizontalLayout_20;
    QVBoxLayout *vLayout_tab_voiceControl;
    QGroupBox *gBox_tab_voiceControlStatus;
    QHBoxLayout *horizontalLayout_35;
    QGridLayout *gLayout_voiceStatus;
    QLabel *label_voiceTask_shakehand;
    QLabel *label_voiceTask_quickStop;
    QLabel *label_voiceStatus;
    QLabel *label_voiceTask_restart;
    QLabel *label_voiceTask_milk;
    QLabel *label_voiceTask_colo;
    QLabel *label_voiceLockStatus;
    QLabel *label_voiceTask_polish;
    QLabel *label_voiceTask_ByBy;
    QGroupBox *gBox_tab_voiceControlOprate;
    QHBoxLayout *horizontalLayout_34;
    QGridLayout *gLayout_voiceOprate;
    QPushButton *btn_closeVoice;
    QPushButton *btn_startVoice;
    QPushButton *btn_lockVoice;
    QPushButton *btn_unlockVoice;
    QWidget *tab_cloudOrder;
    QVBoxLayout *vLayout_9;
    QVBoxLayout *vLayout_cloudOrder_1;
    QGroupBox *gBox_tab_cloudOrder_status;
    QHBoxLayout *horizontalLayout_36;
    QGridLayout *gLayout_tab_cloudOrder_status;
    QLabel *label_cloudOrder_en;
    QLabel *label_cloudOrder_taskDoing;
    QGroupBox *gBox_tab_cloudOrder_operate;
    QHBoxLayout *hLayout_37;
    QGridLayout *gLayout_cloudOrder_operate;
    QPushButton *btn_cloudOrder_start;
    QPushButton *btn_cloudOrder_close;
    QPushButton *btn_cloudOrder_reset;
    QWidget *tab_addfunc;
    QHBoxLayout *horizontalLayout_38;
    QHBoxLayout *hLayout_addfunc;
    QPushButton *btn_tabfsm_avoidingSwitch;
    QPushButton *btn_tabfsm_peopleSwicth;
    QWidget *tab_quickChange;
    QHBoxLayout *horizontalLayout_8;
    QHBoxLayout *hLayout_quickChange_1;
    QVBoxLayout *vLayout_quickChange_11;
    QGroupBox *gBox_quickChange_shelfShow;
    QHBoxLayout *horizontalLayout_24;
    QGridLayout *gLayout_quickChange_shelf;
    QLabel *labelstatus_quickChange_shelf2;
    QLabel *labelstatus_quickChange_shelf3;
    QLabel *labelstatus_quickChange_shelf0;
    QLabel *labeltext_quickChange_shelf1;
    QLabel *labeltext_quickChange_shelf3;
    QLabel *labelstatus_quickChange_shelf1;
    QLabel *labeltext_quickChange_shelf0;
    QLabel *labeltext_quickChange_shelf2;
    QLabel *labeltext_quickChange_rbtool;
    QLabel *labelstatus_quickChange_rbtool;
    QGroupBox *gBox_quickChange_set;
    QHBoxLayout *horizontalLayout_28;
    QGridLayout *gLayout_quickChange_set;
    QComboBox *cBox_quickChange_4finger;
    QLabel *label_quickChange_tool0;
    QLabel *label_quickChange_rbtool;
    QLabel *label_quickChange_tool1;
    QLabel *label_quickChange_tool3;
    QComboBox *cBox_quickChange_tcpTool;
    QComboBox *cBox_quickChange_twofinger;
    QLabel *label_quickChange_tool2;
    QComboBox *cBox_quickChange_fivefinger;
    QComboBox *cBox_quickChange_nopower;
    QPushButton *btn_quickChange_activateSet;
    QPushButton *btn_quickChange_importSet;
    QGroupBox *gBox_quickChange_switchTool;
    QHBoxLayout *horizontalLayout_25;
    QComboBox *cBox_quickChange;
    QPushButton *btn_quickChange_switch;
    QPushButton *btn_quickstop;
    QWidget *tab_fivefinger;
    QHBoxLayout *horizontalLayout;
    QHBoxLayout *hLayout_tab_fivefinger_1;
    QVBoxLayout *vLayout_tab_fivefinger_11;
    QTabWidget *tablewidge_fivefinger;
    QWidget *tablewidge_fivefinger_peopleshow;
    QHBoxLayout *horizontalLayout_26;
    QLabel *lable_tab_fivefinger_peopleshow;
    QVBoxLayout *vLayout_tab_fivefinger_12;
    QGroupBox *gBox_tab_fivefinger_fsm;
    QHBoxLayout *horizontalLayout_17;
    QGridLayout *gLayout_tab_fivefinger_fsm;
    QLabel *lablestatus_tab_fivefinger_fivefinger;
    QLabel *lablestatus_tab_fivefinger_init;
    QLabel *lablestatus_tab_fivefinger_shakehand;
    QLabel *lablestatus_tab_fivefinger_err;
    QLabel *lablestatus_tab_fivefinger_exit;
    QLabel *lablestatus_tab_fivefinger_switchgripper;
    QGroupBox *gBox_tab_fivefinger_sysoprate;
    QHBoxLayout *horizontalLayout_18;
    QGridLayout *gdLayout_tab_fivefinger;
    QPushButton *btn_tab_fivefinger_activate;
    QPushButton *btn_tab_fivefinger_stop;
    QGroupBox *gBox_tab_fivefinger_operate;
    QVBoxLayout *verticalLayout_10;
    QTabWidget *tabWidget_tab_fivefinger;
    QWidget *tab_tab_fivefinger_shakehand;
    QHBoxLayout *horizontalLayout_19;
    QPushButton *btn_tab_fivefinger_shakehand;
    QPushButton *btn_tab_fivefinger_StopShakehand;
    QWidget *tab_tab_fivefinger_switchfsmstatus;
    QHBoxLayout *horizontalLayout_21;
    QPushButton *btn_tab_fivefinger_backswitchGripper;
    QWidget *tab_nopowerTool;
    QVBoxLayout *verticalLayout_3;
    QTabWidget *tabWidget_tab_nopowerTool;
    QWidget *tab_tab_nopowerTool_func;
    QVBoxLayout *verticalLayout;
    QGroupBox *gBox_tab_nopowerTool_status;
    QHBoxLayout *horizontalLayout_6;
    QGridLayout *gLayout_tab_nopowerTool;
    QLabel *labelstatus_tab_nopower_main;
    QLabel *labelstatus_tab_nopower_nopowerEn;
    QLabel *labelstatus_tab_nopower_nopowerRun;
    QLabel *labelstatus_tab_nopower_switchGripper;
    QGroupBox *gBox_tab_nopower_oprate;
    QHBoxLayout *horizontalLayout_10;
    QGridLayout *gLayout_tab_nopower_operate;
    QPushButton *btn_tab_nopower_beginRun;
    QPushButton *btn_tab_nopower_stoprun;
    QPushButton *btn_tab_nopower_backSwitchGripper;
    QPushButton *btn_tab_nopower_quickstop;
    QWidget *tab_tab_nopowerTool_setTool;
    QVBoxLayout *verticalLayout_7;
    QGroupBox *gBox_ab_nopower_testPose;
    QHBoxLayout *horizontalLayout_27;
    QGridLayout *gLayout_nopower_testPose;
    QPushButton *btn_polish_stepMoveActivate;
    QLabel *label_polish_loopTestStatus;
    QLabel *label_polish_stepTestStatus;
    QPushButton *btn_polish_loopMoveActivate;
    QLabel *label_polish_testProgress;
    QLabel *labelValue_polish_testProgress;
    QGroupBox *gBox_ab_nopower_func;
    QHBoxLayout *horizontalLayout_37;
    QHBoxLayout *hLayout_tabPolish_testTab1;
    QPushButton *btn_polish_stepMove;
    QPushButton *btn_polish_goHome;
    QPushButton *btn_polish_loopMove;
    QPushButton *btn_polish_exitTest;
    QPushButton *btn_tab_nopower_Activate;
    QWidget *tab_fourfingerTool;
    QHBoxLayout *horizontalLayout_42;
    QHBoxLayout *hLayout_fourfingerTool_1;
    QVBoxLayout *vLayout_fourfingerTool11;
    QGroupBox *gBox_tab_fourfingerTool_yolo6d;
    QHBoxLayout *horizontalLayout_45;
    QLabel *label_tab_fourfingerTool_yolo6dShow;
    QVBoxLayout *vLayout_fourfingerTool12;
    QGroupBox *gBox_tab_fourfingerTool_status_2;
    QHBoxLayout *horizontalLayout_43;
    QGridLayout *gLayout_tab_fourfingerTool;
    QLabel *labelstatus_fourfinger_main;
    QLabel *labelstatus_fourfingerToolEn;
    QLabel *labelstatus_fourfingerTool_grab;
    QLabel *labelstatus_fourfingerswitchGripper;
    QGroupBox *gBox_tab_fourfingerTool_oprate;
    QHBoxLayout *horizontalLayout_44;
    QGridLayout *gLayout_tab_fourfingerTool_operate;
    QPushButton *btn_fourfingerTool_Activate;
    QPushButton *btn_fourfinger_Grab;
    QPushButton *btn_fourfinger_backSwitchGripper;
    QPushButton *btn_fourfinger_quickstop;

    QWidget *tab_sorting;
    QHBoxLayout *hLayout_tab_sorting_27;
    QTabWidget *tabWidget_sort;
    QWidget *tab_tabsort_func;
    QVBoxLayout *verticalLayout_8;
    QGroupBox *gBox_tabsort_status;
    QHBoxLayout *horizontalLayout_39;
    QGridLayout *gLayout_tabsort_status;
    QLabel *label_tabsort_sortToolEnable;
    QLabel *label_tabsort_mainstatus;
    QLabel *label_tabsort_sortingstatus;
    QLabel *lable_tabsort_backswitchstatus;
    QGroupBox *gBox_tabsort_oprate;
    QHBoxLayout *horizontalLayout_40;
    QGridLayout *gLayout_tabsort_oprate;
    QPushButton *btn_tabsort_backswitchgripper;
    QPushButton *btn_tabsort_stopsort;
    QPushButton *btn_tabsort_beginsort;
    QPushButton *btn_tabsort_activate;
    QPushButton *btn_tabsort_quickstop;
    QWidget *tab_tabsort_calibrate;
    QHBoxLayout *horizontalLayout_41;
    QVBoxLayout *vLayout_tabsort_21;
    QGroupBox *gBox_tabsort_calibrateSet;
    QHBoxLayout *horizontalLayout_46;
    QGridLayout *gLayout_calibrateSet;
    QLabel *label_toolTcp;
    QLineEdit *lineEdit_x;
    QLineEdit *lineEdit_y;
    QLineEdit *lineEdit_z;
    QLineEdit *lineEdit_rx;
    QLineEdit *lineEdit_ry;
    QLineEdit *lineEdit_rz;
    QLabel *label_calibrateNum;
    QLineEdit *lineEdit_calibrateNum;
    QGroupBox *gBox_tabsort_calibrateOprate;
    QHBoxLayout *horizontalLayout_47;
    QGridLayout *gLayout_calibrateOprate;
    QPushButton *btn_calibrateOprate_finish;
    QPushButton *btn_calibrateOprate_initset;
    QPushButton *btn_calibrateOprate_calibrate;
    QPushButton *btn_calibrateOprate_reset;
    QVBoxLayout *vLayout_tabsort_22;
    QGroupBox *gBox_tabsort_calibrateStatus;
    QHBoxLayout *horizontalLayout_49;
    QGridLayout *gLayout_calibrateStatus;
    QLabel *label_calibrateProgress;
    QProgressBar *progressBar_calibrate;
    QGroupBox *gBox_tabsort_calibratedataRecv;
    QHBoxLayout *horizontalLayout_50;
    QPlainTextEdit *plainText_RecvData;

    QWidget *tab_debug;
    QVBoxLayout *verticalLayout_5;
    QTabWidget *tabWidget_tab_debug;
    QWidget *tab_tab_debug_robot;
    QVBoxLayout *verticalLayout_4;
    QGroupBox *gBox_tab_debug_sys;
    QHBoxLayout *horizontalLayout_12;
    QPushButton *btn_tab_debug_reset;
    QPushButton *btn_tab_debug_robEn;
    QGroupBox *gBox_tab_debug_motion;
    QHBoxLayout *horizontalLayout_11;
    QPushButton *btn_tab_debug_backhome;
    QWidget *tab_tab_debug_gripper;
    QVBoxLayout *verticalLayout_6;
    QGroupBox *gBox_tab_debug_fivefinger;
    QHBoxLayout *horizontalLayout_13;
    QPushButton *btn_fivefinger_open;
    QPushButton *btn_fivefinger_close;
    QGroupBox *gBox_tab_debug_fourfinger;
    QHBoxLayout *horizontalLayout_14;
    QPushButton *btn_fourfinger_open;
    QPushButton *btn_fourfinger_close;
    QGroupBox *gBox_tab_debug_twofinger;
    QHBoxLayout *horizontalLayout_15;
    QPushButton *btn_twofinger_open;
    QPushButton *btn_twofinger_close;
    QWidget *tab_tab_debug_poseDebug;
    QHBoxLayout *horizontalLayout_29;
    QHBoxLayout *horizontalLayout_30;
    QVBoxLayout *verticalLayout_14;
    QGroupBox *groupBox_3;
    QHBoxLayout *horizontalLayout_31;
    QPlainTextEdit *plainTextEdit_showPoseInfo;
    QVBoxLayout *verticalLayout_12;
    QGroupBox *gBox_showFileInfo;
    QHBoxLayout *horizontalLayout_32;
    QPushButton *btn_startMoveit;
    QPushButton *btn_tab_debug_openfile;
    QGroupBox *groupBox_2;
    QHBoxLayout *horizontalLayout_33;
    QGridLayout *gridLayout;
    QLabel *label_tab_debug_dirname;
    QPushButton *btn_tab_debug_writePose;
    QLineEdit *lineEdit_dirname;
    QLabel *label_tab_debug_fileName;
    QLineEdit *lineEdit_filename;
    QPushButton *btn_tab_debug_recordPose;
    QLabel *label_poseType;
    QComboBox *cBox_posetype;
    QWidget *tab_recorder;
    QHBoxLayout *horizontalLayout_3;
    QVBoxLayout *vLayout_tab_recorder_1;
    QVBoxLayout *vLayout_tab_recorder_11;
    QPlainTextEdit *plainText_tabrecorder;
    QVBoxLayout *vLayout_tab_recorder_2;
    QPushButton *btn_tab_recoder_ouputRecorder;
    QPushButton *btn_tab_recoder_clearRecorder;
    QStatusBar *statusBar;
};


#endif //RB_UI_BASEWINDOW_H
